project_id = "umluahqqpoimkbidndll"

[functions.send-telegram-notification]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.yookassa-webhook]
verify_jwt = false

[functions.get-bot-info]
verify_jwt = false

[functions.get-busy-slots]
verify_jwt = false